### PR TITLE
adding options menu, return to main menu option button

### PR DESCRIPTION
**Pull request by asunwoo98**
Added an option menu in an attempt to reduce clutter on the screen. Currently only available in the classic mode

### CODE REVIEW

**Comment by charleswdickstein** [comment]
it seems only the restart and back buttons work. FOr simplicity, lets make adjust board its own button as it is a toggle button

**Comment by asunwoo98** [comment]
huh weird thats not the final version i'll redo it

**Comment by koktavy** [comment]
Whoops beat you to it

**Comment by charleswdickstein** [comment]
Looks good. Let's add it to the other game modes. The adjust board button is fine as it is as well.  Good job.

**Pull request merged**
