### PR TITLE
126/127/NewDetectPlatform

### PR DESCRIPTION
**Pull request by koktavy**
Platform detection in the same way as #127. Had issues when merging multiple pull requests without master first.

### CODE REVIEW

**Comment by charleswdickstein** [comment]
The dart is not present/causes errors

**Comment by koktavy** [comment]
How about now? I have had some large-file-storage (lfs) tracking issues and borked something along the way trying to resolve those.

**Comment by koktavy** [comment]
Since I'm having trouble replicating the issue, could either of you copy the missing/broken assets (I think it should only be Dart.fbx and dartImage.png in the Assets folder) from the working master and re-add them to this branch? If I pull with those changes that should add the assets back into my lfs tracking correctly. Thank you!

**Comment by asunwoo98** [comment]
seems to be working now

**Pull request merged**
